[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "dbridge"
version = "0.2.10"
description = ''
readme = "README.md"
requires-python = ">=3.11"
license = "MIT"
keywords = []
authors = [{ name = "realEbi", email = "ebrahim.soroush@gmail.com" }]
classifiers = [
  "Development Status :: 4 - Beta",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: Implementation :: CPython",
  "Programming Language :: Python :: Implementation :: PyPy",
]
dependencies = [
  "pydantic==2.10.4",
  "pydantic-settings==2.7.0",
  "duckdb==1.1.3",
  "sqlglot>=25.0.0",
  "numpy==2.2.1",
  "pandas==2.2.3",
]

[project.optional-dependencies]
mysql = ["pymysql"]
postgres = ["psycopg2"]
snowflake = ["snowflake-connector-python"]

[project.urls]
Documentation = "https://github.com/e3oroush/dbridge#readme"
Issues = "https://github.com/e3oroush/dbridge/issues"
Source = "https://github.com/e3oroush/dbridge"

[dependency-groups]
dev = ["ruff", "black", "isort", "pyright", "pytest", "ipython"]
test = ["coverage[toml]", "pytest", "pytest-cov", "pytest-mock"]
types = ["mypy>=1.0.0"]

[tool.coverage.run]
source_pkgs = ["dbridge", "tests"]
branch = true
parallel = true
omit = ["src/dbridge/__about__.py"]

[tool.coverage.paths]
dbridge = ["src/dbridge", "*/dbridge/src/dbridge"]
tests = ["tests", "*/dbridge/tests"]

[tool.coverage.report]
exclude_lines = ["no cov", "if __name__ == .__main__.:", "if TYPE_CHECKING:"]
